//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaladinGolfWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Attendees = new HashSet<Attendee>();
            this.GameEvents = new HashSet<GameEvent>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int CourseId { get; set; }
    
        public virtual ICollection<Attendee> Attendees { get; set; }
        public virtual Course Course { get; set; }
        public virtual ICollection<GameEvent> GameEvents { get; set; }
    }
}
