//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaladinGolfWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.GameEvents = new HashSet<GameEvent>();
        }
    
        public int Id { get; set; }
        public string GameName { get; set; }
    
        public virtual ICollection<GameEvent> GameEvents { get; set; }
    }
}
