//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaladinGolfWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hole
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public int Hole1 { get; set; }
        public int Par { get; set; }
        public int Handicap { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
